services:


  mail-manage-backoffice:
    build:
      context: ./
    container_name: mail-manage-backoffice
    ports:
      - "3443:${PORT}"
    networks:
      - app-net
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  app-net:
    name: ${CONTAINER_NETWORK}
    external: true


volumes:
  dbdata: